# Generated by Django 3.2.12 on 2022-09-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unique', models.BooleanField()),
                ('loyal', models.BooleanField()),
                ('cost', models.CharField(blank=True, max_length=2, null=True)),
                ('iMilitary', models.BooleanField(blank=True, null=True)),
                ('iIntrigue', models.BooleanField(blank=True, null=True)),
                ('iPower', models.BooleanField(blank=True, null=True)),
                ('strenght', models.CharField(blank=True, max_length=2, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=50, null=True)),
                ('decklimit', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('flavor', models.TextField(blank=True, null=True)),
                ('pIncome', models.CharField(blank=True, max_length=2, null=True)),
                ('pInitiative', models.CharField(blank=True, max_length=2, null=True)),
                ('pClaim', models.CharField(blank=True, max_length=2, null=True)),
                ('pReserve', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.trait')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.pack')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.faction')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.cycle')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('flavor', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.card')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.faction'),
        ),
        migrations.AddField(
            model_name='card',
            name='traits',
            field=models.ManyToManyField(blank=True, to='db.Trait'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.type'),
        ),
    ]
