# Generated by Django 3.2.12 on 2022-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_translatecycle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatefaction',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='translatetrait',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
